ALTER TABLE tenants
  ADD COLUMN IF NOT EXISTS address        TEXT,
  ADD COLUMN IF NOT EXISTS phone          TEXT,
  ADD COLUMN IF NOT EXISTS currency       TEXT NOT NULL DEFAULT 'Rs.',
  ADD COLUMN IF NOT EXISTS receipt_footer TEXT;
